using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;

namespace AbfConvert
{
    public static class CSV
    {
        public static void SaveJaggedArray(float[][] data, string path)
        {
            int columns = data.Length;
            int rows = data.Select(x => x.Length).Max();
            Console.WriteLine($"Saving data with {columns} columns and {rows} rows...");

            // populate 2D array of strings with vaues (or null for empty)
            string[,] valuesText = new string[columns, rows];
            for (int columnIndex = 0; columnIndex < columns; columnIndex++)
                for (int rowIndex = 0; rowIndex < data[columnIndex].Length; rowIndex++)
                    valuesText[columnIndex, rowIndex] = $"{data[columnIndex][rowIndex]}";

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("# CSV file generated by AbfConvert");
            for (int rowIndex = 0; rowIndex < rows; rowIndex++)
            {
                for (int columnIndex = 0; columnIndex < columns; columnIndex++)
                {
                    sb.Append(valuesText[columnIndex, rowIndex]+", ");
                }
                sb.AppendLine();
            }

            System.IO.File.WriteAllText(path, sb.ToString());
        }
    }
}
